// Dataset Bias Auditor (tools/bias-auditor.html): who carries the mistakes.
// One bar per group. Each bar is split at the dark line into the people who
// reoffended (left) and the people who did not (right); the shaded part of a
// bar is everyone the race-blind score flagged as high risk. The shaded area
// to the RIGHT of the line is the false positives - people flagged who did
// not go on to reoffend - and its share of the right-hand part is the false
// positive rate that ProPublica compared across groups.
//
// Data: data/recidivism-sample.csv (synthetic, generated by
// data/generate_samples.py), counted with PredictedRisk = High as "flagged"
// and Recidivated = Yes as "reoffended". Counts below were tallied from that
// file; if the generator changes, re-count and update COUNTS. The same file
// drives the auditor's confusion matrix, so the two should agree.
(function () {
    const root = document.getElementById('fpr-figure');
    if (!root || !window.LineFigure) return;
    const { el, svg: makeSvg, interact } = window.LineFigure;

    // TP: flagged & reoffended   FP: flagged & did not
    // FN: not flagged & reoffended   TN: not flagged & did not
    const COUNTS = [
        { group: 'Black', TP: 108, FP: 80, FN: 34, TN: 75 },
        { group: 'White', TP: 35, FP: 39, FN: 31, TN: 94 },
        { group: 'Hispanic', TP: 22, FP: 14, FN: 10, TN: 22 },
        { group: 'Other', TP: 13, FP: 3, FN: 3, TN: 17 },
    ];
    // Below this many people in the "did not reoffend" stratum, a rate is too
    // noisy to compare - the same threshold the auditor applies (MIN_STRATUM).
    const MIN_STRATUM = 25;

    const X0 = 118, W = 380;        // bar start and width (viewBox units)
    const Y0 = 66, ROW = 46, H = 22; // first bar top, row pitch, bar height
    // The highlight band starts 12 above a bar; the side names above the first
    // bar sit at SIDE_Y, clear of it, flanking that bar's split line.
    const SIDE_Y = Y0 - 18;
    const VW = 600, VH = Y0 + ROW * COUNTS.length - 4;

    const rows = COUNTS.map(c => {
        const n = c.TP + c.FP + c.FN + c.TN;
        const pos = c.TP + c.FN, neg = c.FP + c.TN;
        return { ...c, n, pos, neg, fpr: c.FP / neg, small: neg < MIN_STRATUM };
    });

    const svg = makeSvg(root, `0 0 ${VW} ${VH}`,
        'Four bars, one per group, from the recidivism sample. Each is split into people who reoffended and people who ' +
        'did not; the shaded part is everyone flagged high risk. Among people who did not reoffend, 52 percent of Black ' +
        'defendants were flagged, against 29 percent of White defendants: the same race-blind score, unequal mistakes.');

    // column heads
    el('text', { x: VW - 4, y: 18, 'text-anchor': 'end', class: 'lf-label' }, svg).textContent = 'false-positive rate';
    // legend swatch, starting at the bars' left edge
    el('rect', { x: X0, y: 9, width: 12, height: 10, class: 'lf-shade' }, svg);
    el('text', { x: X0 + 17, y: 18, class: 'lf-label' }, svg).textContent = '= flagged high risk';

    const marks = rows.map((r, i) => {
        const y = Y0 + i * ROW;
        const g = el('g', r.small ? { class: 'lf-ghost' } : {}, svg);
        const band = el('rect', { x: 0, y: y - 12, width: VW, height: ROW - 2, class: 'lf-band' }, g);

        const wPos = W * r.pos / r.n, wNeg = W * r.neg / r.n;
        const split = X0 + wPos;
        // shaded = flagged: TP inside the left part, FP inside the right part
        el('rect', { x: X0, y, width: wPos * r.TP / r.pos, height: H, class: 'lf-shade' }, g);
        const fp = el('rect', { x: split, y, width: wNeg * r.FP / r.neg, height: H, class: 'lf-shade' }, g);
        // the bar outline and the split
        el('rect', { x: X0, y, width: W, height: H, class: 'lf-line' }, g);
        // the first bar's split rises between the two side names above it
        el('line', { x1: split, y1: i === 0 ? SIDE_Y - 9 : y - 4, x2: split, y2: y + H + 4, class: 'lf-line lf-strong' }, g);
        if (i === 0) {
            // name the two sides once, on the first bar, at its own split
            el('text', { x: split - 6, y: SIDE_Y, 'text-anchor': 'end', class: 'lf-label' }, svg).textContent = 'reoffended';
            el('text', { x: split + 6, y: SIDE_Y, class: 'lf-label' }, svg).textContent = 'did not reoffend';
        }

        el('text', { x: X0 - 10, y: y + 10, 'text-anchor': 'end', class: 'lf-label lf-label--head' }, g).textContent = r.group;
        el('text', { x: X0 - 10, y: y + 22, 'text-anchor': 'end', class: 'lf-label' }, g).textContent = `n = ${r.n}`;
        el('text', { x: VW - 4, y: y + 15, 'text-anchor': 'end', class: 'lf-label lf-label--head' }, g)
            .textContent = r.small ? `${r.fpr.toFixed(2)}*` : r.fpr.toFixed(2);
        return { g, fp, band };
    });

    interact({
        root, svg, count: rows.length,
        rest: 'Same race-blind score, unequal mistakes. Pick a group to see its false-positive rate worked out.',
        describe: i => {
            const r = rows[i];
            const base = `${r.group} · ${r.neg} did not reoffend; ${r.FP} of them were flagged · FPR = ${r.FP}/${r.neg} = ${r.fpr.toFixed(2)}`;
            return r.small ? `${base} · too few to compare` : base;
        },
        pick: (x, y) => {
            const i = Math.floor((y - (Y0 - 12)) / ROW);
            return i >= 0 && i < rows.length ? i : -1;
        },
        draw: (glow, active) => {
            marks.forEach((m, i) => {
                const on = i === active;
                m.g.classList.toggle('is-lit', on);
                m.band.classList.toggle('is-lit', on);
                m.fp.classList.toggle('is-lit', on);    // outline the false positives
            });
        }
    });
})();
